[package]
name = "create-argocd-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.7"
dialoguer = "0.11.0"
tinytemplate = "1.2.1"
serde = { version = "1.0", features = ["derive"] }